<div class="hero-unit">
    <h1>
        Welcome to HHF GKB Awards
    </h1>
    <p>
        HHF GKB stands for <em>Harry Hog Football Game and Kick in the Balls
        Awards</em>
    </p>
</div>

<div class="row">
    <div class="span4">
        <h2>Hall of Fame</h2>
        <div ng-repeat='gb in hofData.gameballs'>
            <div>{{gb.total}} - {{gb.name}}</div>
            <div class='progress progress-info'>
                <div class='bar' style='width:{{gb.percent}}%;'></div>
            </div>
        </div>
    </div>
    <div class="span4">
        <h2>Hall of Shame</h2>
        <div ng-repeat='kitb in hofData.kicks'>
            <div>{{kitb.total}} - {{kitb.name}}</div>
            <div class='progress progress-danger'>
                <div class='bar' style='width:{{kitb.percent}}%;'></div>
            </div>
        </div>
    </div>
    <div class="span4">
        <h2>Invite, Share, Spread the word</h2>
        <p>Invite others to listen to the podcast </p>
    </div>
    <div class="span4">
        <h2>Advertisements</h2>
        <p>Advertisements go here</p>
    </div>
</div>
<hr />
<?php echo $this->getContent() ?>
