<?php use Phalcon_Tag as Tag; ?>

<?php echo $this->getContent() ?>

<div class="hero-unit">
    <h1>
        Welcome to HHF GKB Awards
    </h1>
    <p>
        HHF GKB stands for <em>Harry Hog Football Game and Kick in the Balls
        Awards</em>
    </p>
</div>

<div class="row">
    <div class="span4">
        <h2>Manage Invoices Online</h2>
        <p>Create, track and export your invoices online. Automate recurring invoices and design your own invoice using our invoice template and brand it with your business logo. </p>
    </div>
    <div class="span4">
        <h2>Dashboards And Reports</h2>
        <p>Gain critical insights into how your business is doing. See what sells most, who are your top paying customers and the average time your customers take to pay.</p>
    </div>
    <div class="span4">
        <h2>Invite, Share And Collaborate</h2>
        <p>Invite users and share your workload as invoice supports multiple users with different permissions. It helps your business to be more productive and efficient. </p>
    </div>
</div>
