<?php use Phalcon_Tag as Tag; ?>

<?php echo $this->getContent() ?>

<div class='page-header'>
    <h2>Episodes</h2>
</div>

<?php

echo Tag::form(
    array(
        'episodes/add',
        'class' => 'form-horizontal',
    )
)
?>
<fieldset>
    <div class='control-group'>
        <label class='control-label'>Episode</label>
        <div class='controls'>
            <?php echo Tag::textField(array('episodeId', 'class' => 'input-xlarge')) ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>
    <div class='control-group'>
        <label class='control-label'>Date</label>
        <div class='controls'>
            <?php echo Tag::textField(array('episodeDate', 'class' => 'input-xlarge')) ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>
    <div class='control-group'>
        <label class='control-label'>Summary</label>
        <div class='controls'>
            <?php echo Tag::select(array('outcome',array('1' => 'Win', '0' => 'Loss'), 'class' => 'input-xlarge')) ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>
    <div class='control-group'>
        <label class='control-label'>Summary</label>
        <div class='controls'>
            <?php echo Tag::textArea(array('summary', 'rows' => '5', 'class' => 'input-xlarge')) ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>
    <div class='form-actions'>
        <?php echo Tag::submitButton(array('Send', 'class' => 'btn btn-primary btn-large')) ?>
    </div>
</fieldset>
</form>
