<?php use Phalcon_Tag as Tag; ?>

<?php echo $this->getContent() ?>

<div>
    <ul class='nav nav-tabs'>
        <li class='pull-right'>
            <?php echo $addButton; ?>
        </li>
    </ul>
</div>

<div ng-controller='EpisodesCtrl'>
<table class='table table-bordered table-striped ng-cloak' ng-cloak>
    <thead>
    <tr>
        <th><a href='' ng-click="predicate='number'; reverse=!reverse">#</a></th>
        <th><a href='' ng-click="predicate='airDate'; reverse=!reverse">Date</a></th>
        <th><a href='' ng-click="predicate='outcome'; reverse=!reverse">W/L</a></th>
        <th><a href='' ng-click="predicate='summary'; reverse=!reverse">Summary</a></th>
    </tr>
    </thead>
    <tbody>
        <tr ng-repeat="episode in episodesData.results | orderBy:predicate:reverse">
            <td>{{episode.number}}</td>
            <td width='7%'>{{episode.airDate}}</td>
            <td>{{episode.outcome}}</td>
            <td>{{episode.summary}}</td>
            <?php if ($addButton) { ?>
            <td width='1%'><a href='/episodes/edit/{{episode.id}}'><i class='icon-pencil'></i></a></td>
            <td width='1%'><a href='/episodes/delete/{{episode.id}}'><i class='icon-remove'></i></a></td>
            <?php } ?>
        </tr>
    </tbody>
</table>
</div>