<?php use Phalcon_Tag as Tag; ?>

<?php echo $this->getContent() ?>

<div class='page-header'>
    <h2>Awards Entry</h2>
</div>

<p>
    Enter the Game Balls and Kick-In-The-Balls Awards
</p>

<?php

echo Tag::form(
    array(
        'awards/add',
        'class' => 'form-horizontal',
    )
)
?>
<fieldset>
    <div class='control-group'>
        <label class='control-label'>User</label>
        <div class='controls'>
            <?php
            echo Tag::select(
                array(
                    'userId',
                    $users,
                    'using' => array('id', 'username'),
                    'class' => 'input-xlarge',
                )
            ); ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>

    <div class='control-group'>
        <label class='control-label'>Episode</label>
        <div class='controls'>
            <?php
            echo Tag::select(
                array(
                    'episodeId',
                    $episodes,
                    'using' => array('id', 'number'),
                    'class' => 'input-xlarge',
                )
            ); ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>

    <div class='control-group'>
        <label class='control-label'>Player</label>
        <div class='controls'>
            <?php
                echo Tag::select(
                    array(
                        'playerId',
                        $players,
                        'using' => array('id', 'name'),
                        'class' => 'input-xlarge',
                    )
                ); ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>

    <div class='control-group'>
        <label class='control-label'>Award</label>
        <div class='controls'>
            <?php
                echo Tag::selectStatic(
                    array(
                        'award',
                        array('1' => 'Game Ball', '0' => 'Kick In The Balls'),
                        'class' => 'input-xlarge'
                    )
                )
            ?>
            <p class='help-block'>(required)</p>
        </div>
    </div>

    <div class='form-actions'>
        <?php echo Tag::submitButton(array('Save', 'class' => 'btn btn-primary btn-large')) ?>
    </div>
</fieldset>
</form>
