<?php use Phalcon_Tag as Tag; ?>

<?php echo $this->getContent() ?>

<ul class='pager'>
    <li class='previous pull-left'>
        <?php echo Tag::linkTo('awards', '&larr; Go Back') ?>
    </li>
    <li class='pull-right'>
        <?php echo $addButton; ?>
    </li>
</ul>

<div ng-controller='AwardsCtrl'>
    <div class='span6'>
        <h4>Kick In The Balls</h4>
        <table class='table table-bordered table-striped' align='center'>
            <thead>
            <tr>
                <th>Game Balls Hall of Fame</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat='gb in hofData.gameballs'>
                <td>
                    <div>{{gb.total}} - {{gb.name}}</div>
                    <div class='progress progress-info'>
                        <div class='bar' style='width:{{gb.percent}}%;'></div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class='span6'>
        <h4>Kick In The Balls</h4>
        <table class='table table-bordered table-striped' align='center'>
            <thead>
            <tr>
                <th>Kick In The Balls Hall of Fame</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat='kitb in hofData.kicks'>
                <td>
                    <div>{{kitb.total}} - {{kitb.name}}</div>
                    <div class='progress progress-danger'>
                        <div class='bar' style='width:{{kitb.percent}}%;'></div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
