<?php use Phalcon_Tag as Tag; ?>

<?php echo $this->getContent() ?>

<ul class='pager'>
    <li class='pull-right'>
        <?php echo $addButton; ?>
    </li>
</ul>

<div ng-controller='PlayersCtrl'>
    <table class='table table-bordered table-striped' align='center'>
        <thead>
        <tr>
            <th><a href='' ng-click="predicate='name'; reverse=!reverse">Name</a></th>
            <th><a href='' ng-click="predicate='active'; reverse=!reverse">Active</a></th>
            <th><a href='' ng-click="predicate='team'; reverse=!reverse">Info</a></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="player in playersData.results | orderBy:predicate:reverse">
            <td>{{player.name}}</td>
            <td>{{player.active}}</td>
            <?php if ($addButton) { ?>
            <td width='1%'><a href='/players/edit/{{player.id}}'><i class='icon-pencil'></i></a></td>
            <td width='1%'><a href='/players/delete/{{player.id}}'><i class='icon-remove'></i></a></td>
            <?php } ?>
        </tr>
        </tbody>
    </table>
</div>