
<p><h1>About HHF GKB Awards</h1></p>

<p>
    This application was written as a fun project, but also to showcase the
    power of the <a href="http://phalconphp.com">Phalcon PHP Framework</a>, as
    well as <a href='http://angularjs.org'>AngularJS</a>.
</p>
<p>
    The concept is based on the <a href='http://harryhogfootball.com'>Harry Hog Football</a>
    podcast, a podcast from Redskins Fans, to Redskins fans.
</p>
We expect to implement as many features as possible to show how the framework works and its potential.
Please write us if you have any feedback or comments. Feel free to clone the code of this application <a href="https://github.com/phalcon/invo">here</a>
.Thanks!.
