<?php use Phalcon_Tag as Tag; ?>
<!DOCTYPE html>
<html ng-app='HHF'>
    <head>
        <meta charset="utf-8">
        <?php echo Tag::getTitle(); ?>
        <?php echo Tag::stylesheetLink('css/bootstrap-combined.min.css'); ?>
        <?php echo Tag::stylesheetLink('css/style.css'); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Harry Hog Football - Game balls and Kick in the Balls awards finder" />
        <meta name="author" content="niden.net" />

        <?php echo Tag::javascriptInclude('js/jquery.min.js') ?>
        <?php echo Tag::javascriptInclude('js/bootstrap.min.js') ?>
        <?php echo Tag::javascriptInclude('js/angular-1.0.0.min.js') ?>
        <?php echo Tag::javascriptInclude('js/angular-resource-1.0.0.min.js') ?>
        <?php echo Tag::javascriptInclude('js/utils.js') ?>

        <script type='text/javascript'>
        function MenuCtrl($scope) {
            $scope.menus = <?php echo Elements::getMenu($this); ?>;
        }
        function BreadcrumbsCtrl($scope) {
            $scope.breadcrumbs = <?php echo $breadcrumbs; ?>;
        }
        </script>

    </head>
    <body>
    <?php echo $this->getContent() ?>
    </body>
</html>