<?php use Phalcon_Tag as Tag; ?>
<!DOCTYPE html>
<html ng-app='HHF'>
    <head>
        <meta charset="utf-8">
        <?php echo Tag::getTitle(); ?>
        <?php echo Tag::stylesheetLink('css/bootstrap-combined.min.css'); ?>
        <?php echo Tag::stylesheetLink('css/jquery-ui.css'); ?>
        <?php echo Tag::stylesheetLink('css/hhf.css'); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Harry Hog Football - Game balls and Kick in the Balls awards finder" />
        <meta name="author" content="niden.net" />

        <script type='text/javascript'>
        function MenuCtrl($scope) {
            $scope.menus = <?php echo $top_menu; ?>;
        }
        function BreadcrumbsCtrl($scope) {
            $scope.breadcrumbs = <?php echo $breadcrumbs; ?>;
        }
        </script>

    </head>
    <body>

    <div class='navbar'>
        <div class='navbar-inner'>
            <div class='container-fluid ng-cloak' ng-cloak>
                <a class='btn btn-navbar' data-toggle='collapse' data-target='.nav-collapse'>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                </a>
                <a class='brand' href='/'>HHF GKB Awards</a>
                <div class='nav-collapse' ng-controller='MenuCtrl'>
                    <ul class='nav pull-left'>
                        <li ng-repeat='menu in menus.left' ng-class="{true:'active', false:''}[menu.active]">
                            <a href='{{menu.link}}'>{{menu.text}}</a>
                        </li>
                    </ul>
                    <ul class='nav pull-right'>
                        <li>
                            <img id='spinner' class='spinner' src='/img/loader.gif' alt='Loading...' />
                        </li>
                        <li>
                            <a href='{{menus.rightLink}}'>{{menus.rightText}}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class='container-fluid'>
        <div class='row-fluid ng-cloak' ng-cloak ng-controller='BreadcrumbsCtrl'>
            <ul class='breadcrumb'>
                <li ng-repeat='bc in breadcrumbs'>
                    <div ng-switch on='bc.active' >
                        <div ng-switch-when='true'>
                            {{bc.text}}
                        </div>
                        <div ng-switch-default>
                            <a href='{{bc.link}}'>{{bc.text}}</a> <span class='divider'>/</span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="row-fluid">
            <?php echo $this->getContent() ?>
        </div> <!-- row -->
        <hr />
        <footer>
            <p>&copy; niden.net <?php echo date('Y'); ?></p>
        </footer>
    </div>

    <?php echo Tag::javascriptInclude('js/jquery.min.js') ?>
    <?php echo Tag::javascriptInclude('js/jquery-ui.min.js') ?>
    <?php echo Tag::javascriptInclude('js/bootstrap.min.js') ?>
    <?php echo Tag::javascriptInclude('js/angular-1.0.0.min.js') ?>
    <?php echo Tag::javascriptInclude('js/angular-resource-1.0.0.min.js') ?>
    <?php echo Tag::javascriptInclude('js/angular-ui.js') ?>
    <?php echo Tag::javascriptInclude('js/utils.js') ?>

    </body>
</html>