    <div class='navbar navbar-fixed-top'>
        <div class='navbar-inner'>
            <div class='container-fluid'>
                <a class='btn btn-navbar' data-toggle='collapse' data-target='.nav-collapse'>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                </a>
                <a class='brand' href='/'>HHF GKB Awards</a>
                <div class='nav-collapse' ng-controller='MenuCtrl'>
                    <ul class='nav pull-left'>
                        <li ng-repeat='menu in menus.left' ng-class="{true:'active', false:''}[menu.active]">
                            <a href='{{menu.link}}'>{{menu.text}}</a>
                        </li>
                    </ul>
                    <ul class='nav pull-right'>
                        <li>
                            <a href='{{menus.rightLink}}'>{{menus.rightText}}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class='container-fluid'>
        <div  ng-controller='BreadcrumbsCtrl'>
            <ul class='breadcrumb'>
                <li ng-repeat='bc in breadcrumbs'>
                    <div ng-switch on='bc.active' >
                        <div ng-switch-when='true'>
                            {{bc.text}}
                        </div>
                        <div ng-switch-default>
                            <a href='{{bc.link}}'>{{bc.text}}</a> <span class='divider'>/</span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="row-fluid">
            <?php echo $this->getContent() ?>
        </div> <!-- row -->
        <hr />
        <footer>
            <p>&copy; niden.net <?php echo date('Y'); ?></p>
        </footer>
    </div>
