    <div class='navbar navbar-fixed-top'>
        <div class='navbar-inner'>
            <div class='container'>
                <a class='btn btn-navbar' data-toggle='collapse' data-target='.nav-collapse'>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                </a>
                <a class='brand' href='#'>HHF GKB Awards</a>
                <div class='nav-collapse' ng-controller='MenuCtrl'>
                    <ul class='nav pull-left'>
                        <li ng-repeat='menu in menus.left' ng-class="{true:'active', false:''}[$index==menu.current]">
                            <a href='{{$menu.link}}'>{{menu.text}}</a>
                        </li>
                    </ul>
                    <ul class='nav pull-right'>
                        <li ng-repeat='menu in menus.right'>
                            <a href='{{$menu.link}}'>{{menu.text}}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class='container'>
        <div ng-controller='BcCtrl'>
            <ul class='breadcrumb'>
                <li ng-repeat="bc in breadcrumbs" ng-class="{true:'active', false:''}[$index==breadcrumb.current]">
                    <a href="{{bc.link}}">{{bc.text}}</a> <span class="divider">/</span>
                </li>
            </ul>
        </div>
        <?php echo $this->getContent() ?>
        <hr>
        <footer>
            <p>&copy; niden.net <?php echo date('Y'); ?></p>
        </footer>
    </div>
